name: merge-lib-files
on: [push]
jobs:
  merge-lib-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g concat-files-cli
      - run: concat-files-cli -i ./lib/* -o ./release/lib.js
