name: merge-lib-files
on: [push]
jobs:
  merge-lib-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: codevise/documentation-js-action@v1
        with:
          input: ./release
          output: ./docs
