name: jsdoc
on:
 [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./release
        recurse: true
        output_dir: ./out
        
# Auto-commit to repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: concatenated lib files
        branch: ${{ github.ref }}
