name: jsdoc
on:
 [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./release
        recurse: true
        output_dir: ./out
